version: '3'

services:
  api:
    image: undeadops/mole:latest
    command: mole
    ports:
      - "5000:5000"
    environment:
      - ACCESS-TOKEN=<TwitterAccess Token>
      - ACCESS-SECRET=<TwitterAccess Secret>
      - CONSUMER-KEY=<TwitterConsumer Key>
      - CONSUMER-SECRET=<TwitterConsumer Secret>
      - PORT=":5000"
      - TRACK: "#AWS"
